### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by yuki526** [yuki526/furima-32050#9]
- URL
https://furima-32050.herokuapp.com/

- Basic認証
　ID:   admin
　PW: 1234

- 出品者情報（ユーザー１）
　Email: aaa@aaa
　PW:    1234qwer

- 購入者情報（ユーザー２）
　Email: sss@sss
　PW:    1234qwer

- カード情報
　番号:        4242424242424242
　有効期限: 12月 / 23年（未来の日付なら任意で可能）
　cvc:          123

どうぞよろしくお願いいたします。

**Comment by mo1015** [comment]
上山さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます:tada:
おめでとうございます！
**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**

**Comment by yuki526** [comment]
挙動確認いただきありがとうございました！
今後ともよろしくお願いいたします。
